### ISSUE TITLE
Change button color

### ISSUE THREAD

**Issue by clairecharles** [Recoded-Spark-Turkey-2022/Venus#59]
## Description
The buttons can't be seen clearly without being hovered on.

![Screenshot 2023-01-03 at 10 48 02](https://user-images.githubusercontent.com/67120042/210333878-9f93485b-2990-4047-803e-3fcb43e70aaa.png)

## Steps to Reproduce

1. Change the button color
2. Change the text color on the button

**Comment by dilaracetinberk** [comment]
Thank you, it has been solved, not merged yet
